// @file: @/seeder/placeholder-data.ts
import { IDrink } from '@/backend/models/interfaces';
import { DrinkCategory, RetailChain, Country } from '@/backend/models/enums';
// import { RetailPrices, DrinkVolume } from '@/backend/models/types';

const beveragesData:IDrink[] = [
  /* --- BOURBON --- */
  {
    id: 1001,
	title: 'Wild Turkey Rare Breed 0.7L',
    category: DrinkCategory.Bourbon,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 1669, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country.USA,
    description: 'Тони паленого коричневого цукру і ванілі, трохи цитрусових, сосни і дуба.'
  },
  {
    id: 1002,
	title: 'Wild Turkey Longbranch 0.7L',
    category: DrinkCategory.Bourbon,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 1637, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country.USA,
    description: 'Смак з відтінками димних солодощів, червоних яблук і карамелі. '
  },
  {
    id: 1003,
	title: 'Wild Turkey 101 0.7L',
    category: DrinkCategory.Bourbon,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 1049, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country.USA,
    description: 'Смак ванілі, меду, карамелі, тютюну і тростинного цукру. Аромат ванілі, дуба, апельсина.'
  },
  {
    id: 1004,
	title: 'Wild Turkey 0.7L',
    category: DrinkCategory.Bourbon,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 849, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 589, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country.USA,
    description: 'Аромат ірису, меду, карамелі і обпаленого дуба. Делікатний, солодкуватий, трохи маслянистий смак.'
  },
  {
    id: 1005,
	title: 'Wild Turkey Rye 0.7L',
    category: DrinkCategory.Bourbon,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 849, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country.USA,
    description: 'Аромат має ванільно-пряні, дубові, цитрусові акценти. У смаку грушеві тони в компанії карамелі.'
  },
  {
    id: 1006,
	title: 'Jim Beam Double Oak 0.7L',
    category: DrinkCategory.Bourbon,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 1089, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 1199, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country.USA,
    description: 'Баланс насиченого смаку і неповторного аромату.'
  },
  {
    id: 1007,
	title: 'Jim Beam Double Rye 0.7L',
    category: DrinkCategory.Bourbon,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 'none', lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 1179, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country.USA,
    description: ''
  },
  {
    id: 1008,
	title: 'Jim Beam White 4Y 0.7L',
    category: DrinkCategory.Bourbon,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 559, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 549, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country.USA,
    description: '51% сусла із кукурудзи.'
  },
  {
    id: 1011,
	title: 'Wild Turkey 1.0L',
    category: DrinkCategory.Bourbon,
    volume: 1.0,
    prices: {
      [RetailChain.Auchan]: { price: 1045, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 'none', lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country.USA,
	description: 'Аромат ірису, меду, карамелі і обпаленого дуба. Делікатний, солодкуватий, трохи маслянистий смак.'
  },
  {
    id: 1012,
	title: 'Jim Beam Red Stag Cherry 1.0L',
    category: DrinkCategory.Bourbon,
    volume: 1.0,
    prices: {
      [RetailChain.Auchan]: { price: 'none', lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 1159, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country.USA,
    description: ''
  },
  {
    id: 1013,
	title: 'Jim Beam White 4Y 1.0L',
    category: DrinkCategory.Bourbon,
    volume: 1.0,
    prices: {
      [RetailChain.Auchan]: { price: 729, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 1159, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country.USA,
    description: '51% сусла із кукурудзи.'
  },
  /* --- WHISKEY --- */
  {
    title: 'Ballantines',
    category: DrinkCategory.Whiskey,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country,
    id: 108,
  },
  {
    title: 'Jameson',
    category: DrinkCategory.Whiskey,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country,
    id: 109,
  },
  {
    title: 'Jameson',
    category: DrinkCategory.Whiskey,
    volume: 0.5,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country,
    id: 110,
  },
  {
    title: 'Ballantines',
    category: DrinkCategory.Whiskey,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country,
    id: 111,
  },
  {
    title: 'John Walker',
    category: DrinkCategory.Whiskey,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 4,
    country: Country,
    id: 112,
  },
  {
    title: 'John Walker',
    category: DrinkCategory.Whiskey,
    volume: 0.5,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 4,
    country: Country,
    id: 113,
  },
  /* --- RUM --- */
  {
    id: 1010
	title: 'Doorly\'s Gold 5Y 0.7L',
    category: DrinkCategory.Rum,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 980, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country.Barbados,
    description: 'Ноти тропічних і сушених фруктів, підсмажених кокосів і дуба. Післясмак фруктовий ванільний.'
  },
  {
    id: 104,
	title: 'Doorly\'s White 3Y 0.7L',
    category: DrinkCategory.Rum,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 865, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country.Barbados,
    description: 'Ванільний аромат із вершковими та медовими нотками. Смак з відтінками екзотичних фруктів.'
  },
  {
    id: 1005,
	title: 'Botafogo Spiced 0.7L',
    category: DrinkCategory.Rum,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 649, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country.Belgium,
    description: 'У смаку - спеції, ваніль, карамель і лакриця. Аромат солодкий цитрусовий.'
  },
  {
    id: 1007,
	title: 'Appleton Reserve 0.7L',
    category: DrinkCategory.Rum,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 642, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 4,
    country: Country.Jamaica,
    description: 'Cмак пряних і горіхових нот із відтінком меду, ванілі і лісового горіха.'
  },
  {
    id: 1008,
	title: 'Appleton 12Y 0.7L',
    category: DrinkCategory.Rum,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 1299, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 0,
    country: Country.Jamaica,   
	description: 'Вершковий смак із відтінками апельсинової цедри і ванілі. Аромат волоського і мускатного горіхів.'
  },
  {
    id: 1003,
	title: 'Santiago de Cuba Anejo 0.7L',
    category: DrinkCategory.Rum,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 599, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country.Cuba,
    description: 'Гладкий смак із фруктовими відтінками, нюансами вишні, ванілі, какао.'
  },
  {
    id: 1009,
	title: 'Bacardi Spiced 0.7L',
    category: DrinkCategory.Rum,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 'none', lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country.Italy,
    description: 'Ваніль, кориця, мускатний горіх і мед. Аромат з нотками дубової бочки і сухофруктів.'
  },
    {
    id: 1003,
	title: 'Santiago de Cuba Carta Blanca 0.7L',
    category: DrinkCategory.Rum,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 399, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 2,
    country: Country.Cuba,
    description: 'Квітковий аромат із відтінками меду і карамелі. Свіжий цитрусовий смак.'
  },
  {
    id: 1006,
	title: 'Botafogo Black 0.7L',
    category: DrinkCategory.Rum,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 972, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 2,
    country: Country.Belgium,
    description: 'Темний ром, ваніль, апельсин, чилі. Аромат висушеного винограду.'
  },
  {
    title: 'Santiago Cuba',
    category: DrinkCategory.Rum,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country.Cuba,
    id: 122,
  },
  {
    id: 1019,
	title: 'Bacardi Spiced 1.0L',
    category: DrinkCategory.Rum,
    volume: 1.0,
    prices: {
      [RetailChain.Auchan]: { price: 569, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country.Italy,
    description: 'Ваніль, кориця, мускатний горіх і мед. Аромат з нотками дубової бочки і сухофруктів.'
  },
  /* --- GIN --- */
  {
    title: 'Gordon\'s',
    category: DrinkCategory.Gin,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 4,
    country: Country,
    id: 114,
  },
  {
    title: 'Colonist',
    category: DrinkCategory.Portwein,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country.Ukraine,
    id: 115,
  },
  {
    title: 'Osborn',
    category: DrinkCategory.Portwein,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country,
    id: 116,
  },
  {
    title: 'Colonist',
    category: DrinkCategory.Champagne,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country.Ukraine,
    id: 117,
  },
  {
    title: 'Martini',
    category: DrinkCategory.Champagne,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country,
    id: 118,
  },
  {
    title: 'Espolon',
    category: DrinkCategory.Tequila,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country,
    id: 119,
  },
  {
    title: 'Espolon',
    category: DrinkCategory.Tequila,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country,
    id: 120,
  },
  {
    title: 'Jagermeister',
    category: DrinkCategory.Tincture,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country,
    id: 123,
  },
  {
    title: 'Jagermeister',
    category: DrinkCategory.Tincture,
    volume: 1.0,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country,
    id: 124,
  },
  {
    title: 'Becherovka',
    category: DrinkCategory.Tincture,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country,
    id: 125,
  },
  {
    title: 'Becherovka',
    category: DrinkCategory.Tincture,
    volume: 0.5,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country,
    id: 126,
  },
  {
    title: 'R.Jelinek',
    category: DrinkCategory.Tincture,
    volume: 0.5,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country,
    id: 127,
  },
  {
    title: 'Absolut',
    category: DrinkCategory.Horilka,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 4,
    country: Country,
    id: 128,
  },
  {
    title: 'Finlandia',
    category: DrinkCategory.Horilka,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country.Finland,
    id: 129,
  },
  {
    title: 'Finlandia',
    category: DrinkCategory.Horilka,
    volume: 0.5,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-11-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-11-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country.Finland,
    id: 130,
  },
];